mongo_username = "username"
mongo_password = "password"
mongo_clustername = "clustername"
mongo_clusterlink = "clusterlink"
mongo_clientname = "new_clientname"
mongo_collectionname = "new_collectionname"
data_path = f"Absolute_path"  # Please use this sign: "/" instead of this sign: "\" in your absolute path
google_cloud_service_key = f"Absolute_path"  # Please use this sign: "/" instead of this sign: "\" in your absolute path
bucket_name = "new_bucketname"
blob_name = "new_blobname"
symbol_of_current_currency = "symbol_of_currency"  # Rupi
symbol_of_new_currency = "symbol_of_currency"  # TL
exchange_rate_current_to_new_currency = "exchange_rate"  # Please let your input be float
column_to_convert_1 = "column_name"
column_to_convert_2 = "column_name"
